package uy.gub.dgr.sur.entity;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Celda3G.java
//  @ Date : 11/12/2013
//  @ Author : 
//
//


import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import org.hibernate.envers.Audited;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

@Entity
@Data
@ToString(exclude = "nodo3G")
@EqualsAndHashCode(callSuper = true, exclude = {"nodo3G", "feeder", "largoFeeder", "atenuacion", "tipoFeeder", "scramblingCode"})
@DiscriminatorValue("3G")
@Audited
public class Celda3G extends Celda {


    private String feeder;

    private Float largoFeeder;

    private Float atenuacion;

    private Integer scramblingCode;

    @ManyToOne
    private TipoFeeder tipoFeeder;

    @ManyToOne
    private Nodo3G nodo3G;

}
